version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/flask_app
hooks:
  BeforeInstall:
    - location: flask_app_shutdown.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: codedeploy_start.sh
      timeout: 180
      runas: root
