version: '3'
services:
  nginx:
#    image: nginx:1.15
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./source/react/public:/usr/src
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  nginx_vue:
#    image: nginx:1.15
    build: ./nginx_vue
    ports:
      - 8000:8000
    volumes:
      - ./source/vuef/dist:/usr/src
      - ./nginx_vue/default.conf:/etc/nginx/conf.d/default.conf

  python3:
    build: ./python3
    ports:
      - 5000:5000
    volumes:
      - ./source:/var/www/html
    tty: true
    privileged: true
    working_dir: /var/www/html/application

  go_server:
    build: ./go_server
    ports:
      - 5001:5001
    volumes:
      # for local
#      - /Users/takaki/go/src/go_weather:/go/src/go_weather
      # for aws
      - /home/ec2-user/go_app:/go/src/go_weather
    tty: true
    privileged: true
    working_dir: /go
    command: sh setup.sh

  mysql:
      image: mysql:8.0
      environment:
        MYSQL_DATABASE: weather_db
        MYSQL_ROOT_PASSWORD: password
        MYSQL_USER: sample_user
        MYSQL_PASSWORD: password
        TZ: Asia/Tokyo
      ports:
        - 3306:3306
      volumes:
        - ./mysql/data:/var/lib/mysql
        - ./mysql/init:/docker-entrypoint-initdb.d
        - ./mysql/conf:/etc/mysql/conf.d

  redis:
    image: redis:latest
    ports:
      - 6379:6379
